### PR TITLE
ios : try reconnect on unexpected disconnection

### PR DESCRIPTION
**Pull request by EB-Plum**
on android, bluetooth automatically reconnect after unexpected disconnection. (eg. device too far) 
on ios, it doesn't.
i had a same issue as [this](https://github.com/pauldemarco/flutter_blue/issues/857#issue-908397368)
I dont know if ios does it on purpose...

### CODE REVIEW

**Comment by fabiototh** [comment]
Hi, I'm get this error: PlatformException(connect, Peripheral not found, null, null).
Device is connect bluetooth iOS. But in flutter blue the state is disconnected. When I try connect, return this.

**Comment by trueb2** [comment]
> Hi, I'm get this error: PlatformException(connect, Peripheral not found, null, null).
> Device is connect bluetooth iOS. But in flutter blue the state is disconnected. When I try connect, return this.

This PR is about detecting an erroneous disconnection and setting a pending connection. If your BLE device is connected to iOS already, it would not trigger this logic. You can search for already connected peripherals (who wouldn't be firing the didDiscover hook) with
https://developer.apple.com/documentation/corebluetooth/cbcentralmanager/1518924-retrieveconnectedperipheralswith.

There is code available via getConnectedDevices that will look for all currently connected devices.
```
  } else if([@"getConnectedDevices" isEqualToString:call.method]) {
    // Cannot pass blank UUID list for security reasons. Assume all devices have the Generic Access service 0x1800
    NSArray *periphs = [self->_centralManager retrieveConnectedPeripheralsWithServices:@[[CBUUID UUIDWithString:@"1800"]]];
    NSLog(@"getConnectedDevices periphs size: %lu", [periphs count]);
    result([self toFlutterData:[self toConnectedDeviceResponseProto:periphs]]);
    ```

**Comment by boskokg** [comment]
fixed on flutter_blue_plus 1.1.0

**Comment by fabiototh** [comment]
> fixed on flutter_blue_plus 1.1.0

I have more fixes in a fork that would be nice to contain in your package.

**Comment by boskokg** [comment]
@fabiototh can you please put merge requests to the new plugin flutter_blue_plus so we can add all fixes that you have?

**Pull request closed without merging**
