### PR TITLE
On Android OS 12 scanning for devices would crash when trying to get the name of the Bluetooth device because it needed BLUETOOTH_CONNECT permissions to do so.

### PR DESCRIPTION
**Pull request by dspells**
This is the first time I've made a pull request. I hope that I'm doing this right.

See https://github.com/boskokg/flutter_blue/issues/19 for the stack crawl.

### CODE REVIEW

**Review by zimzf23 — APPROVED** [review]
Had the same error, worked perfectly for me

**Comment by dspells** [comment]
What is the next step in getting this request merged in?

**Comment by espresso3389** [comment]
I've create a new PR #29 that applies addtional fix on pauldemarco/flutter_blue#940, which also includes the fix for the issue.

**Comment by boskokg** [comment]
@dspells the current code checks for permissions in the code that called startScan method:


 ```
case "startScan":
  {
    ensurePermissionBeforeAction(Build.VERSION.SDK_INT >= Build.VERSION_CODES.S ? Manifest.permission.BLUETOOTH_SCAN : Manifest.permission.ACCESS_FINE_LOCATION, (granted, permission) -> {
      if (granted)
        startScan(call, result);
      else
        result.error(
                "no_permissions", String.format("flutter_blue plugin requires %s for scanning", permission), null);
    });
    break;
  }
```

I don't this it is the clean code to do checks in the two places like you proposed. Can you please fix it?

 Note: We published the flutter_blue_plus plugin, so please make PR there.

**Pull request closed without merging**
